services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: usersample
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  nodeapp:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: usersample
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
